// app/layout.js (serveur)
// import { Geist, Geist_Mono } from "next/font/google";
import "@/styles/globals.css";
import AnalyticsTracker from "@/components/AnalyticsTracker";
import { Geist, Geist_Mono } from "next/font/google";
import ClientProvider from "./ClientProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fr">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <AnalyticsTracker />
        <ClientProvider>
          {children}
        </ClientProvider>
      </body>
    </html>
  );
}
